
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ERROR_CATEGORIES = 'ERROR_CATEGORIES';
export const GETBYID_CATEGORY = 'GETBYID_CATEGORY';


