const ActionsCategoryTypes = {
  ADD_CATEGORY: {
    ADD_CATEGORY: 'ADD_CATEGORY'
  },
  EDIT_CATEGORY: {
    EDIT_CATEGORY: 'EDIT_CATEGORY'
  },
  REMOVE_CATEGORY: {
    REMOVE_CATEGORY: 'REMOVE_CATEGORY'
  },
  GET_CATEGORIES: {
    GET_CATEGORIES: 'GET_CATEGORIES'
  },
  ERROR_CATEGORIES: {
    ERROR_CATEGORIES: 'ERROR_CATEGORIES'
  }
}
export {ActionsCategoryTypes};


