export const ADD_CURRENCY = 'ADD_CURRENCY';
export const EDIT_CURRENCY = 'EDIT_CURRENCY';
export const REMOVE_CURRENCY = 'REMOVE_CURRENCY';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const ERROR_CURRENCIES = 'ERROR_CURRENCIES';
export const GETBYID_CURRENCY = 'GETBYID_CURRENCY';



