export const ADD_MOVEMENT = 'ADD_MOVEMENT';
export const EDIT_MOVEMENT = 'EDIT_MOVEMENT';
export const REMOVE_MOVEMENT = 'REMOVE_MOVEMENT';
export const GET_MOVEMENTS = 'GET_MOVEMENTS';
export const ERROR_MOVEMENTS = 'ERROR_MOVEMENTS';
export const GETBYID_MOVEMENT = 'GETBYID_MOVEMENT';



